#!/bin/bash
# GitHub CLI setup helper

echo "GitHub CLI Setup"
echo "================"
echo ""
echo "To give me GitHub access, choose one option:"
echo ""
echo "OPTION 1: Personal Access Token (Easiest)"
echo "-------------------------------------------"
echo "1. Go to: https://github.com/settings/tokens/new"
echo "2. Select 'repo' scope"
echo "3. Generate token"
echo "4. Paste token here:"
echo ""
echo "OPTION 2: Device Flow"
echo "----------------------"
echo "1. Run: gh auth login"
echo "2. Choose 'Login with a web browser'"
echo "3. Enter the code shown"
echo ""
echo "OPTION 3: Manual Config"
echo "-----------------------"
echo "Create file: ~/.config/gh/hosts.yml"
echo "With content:"
echo "github.com:"
echo "    user: YOUR_USERNAME"
echo "    oauth_token: YOUR_TOKEN"
echo "    git_protocol: https"
